trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.x'
  AZURE_STORAGE_ACCOUNT_NAME: $(AZURE_STORAGE_ACCOUNT_NAME)
  AZURE_STORAGE_ACCOUNT_KEY:  $(AZURE_STORAGE_ACCOUNT_KEY)
  AZURE_CONTAINER_NAME:       $(AZURE_CONTAINER_NAME)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      python Data_processing.py
    displayName: 'Run data cleaning & enrichment'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'Data\processed_sales_data2.csv'
      artifact: 'sales_data_artifacts'
      publishLocation: 'pipeline'
    displayName: 'Publish raw & processed CSV files'
